steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/statusman', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/statusman']
  
  # Deploy container image to Cloud Run with explicit unauthenticated access
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'statusman'
      - '--image'
      - 'gcr.io/$PROJECT_ID/statusman'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORTNO=8080,PROMETHEUS_SYNC_ENABLED=true,CORS_ORIGIN=https://frontend-pi-seven-10.vercel.app'

images:
  - 'gcr.io/$PROJECT_ID/statusman'
